DEF VBLANKY         EQU $90
DEF OAM_SIZE        EQU $00A0
DEF HEADER_SIZE     EQU $150
DEF TILES_START     EQU $9010
DEF TILEMAP_START   EQU $9800

DEF PlayerDown      EQU $80
DEF PlayerUp        EQU $40
DEF PlayerLeft      EQU $10
DEF PlayerRight     EQU $20

DEF PlayerMinHeight EQU $9833
DEF PlayerMaxHeight EQU $9A20

DEF ColumnMask      EQU $1F
DEF RowMaskLow      EQU $E0


DEF WrapUpRow       EQU $9A
DEF WrapDownRow     EQU $98